language: php

php:
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer install

before_script:
  - mysql -e 'create database settings_yii2_tests;'
  - php ./tests/yii migrate --migrationPath=./src/migrations --interactive=0

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)
